export const orcamentos = {
  bloco: [
    { item: 'Blocos', quantidade: 337, unidade: 'unidades', valor: 1341.26 },
    { item: 'Cimento', quantidade: 25, unidade: 'sacos', valor: 874.50 },
    { item: 'Areia', quantidade: 2, unidade: 'metros', valor: 359.90 },
    { item: 'Brita', quantidade: 1.5, unidade: 'metros', valor: 300.00 },
    { item: 'Argamassa', quantidade: 1, unidade: 'metro', valor: 189.00 },
    { item: 'Ferro 8mm', quantidade: 10, unidade: 'barras', valor: 399.95 },
    { item: 'Ferro 10mm', quantidade: 4, unidade: 'barras', valor: 199.80 },
    { item: 'Estribos', quantidade: 150, unidade: 'unidades', valor: 147.00 },
    { item: 'Blocos 9x19x39', quantidade: 80, unidade: 'unidades', valor: 308.00 },
    { item: 'Tábuas 30cm', quantidade: 6, unidade: 'unidades', valor: 173.40 },
    { item: 'Réguas 15cm', quantidade: 6, unidade: 'unidades', valor: 83.70 },
    { item: 'Prego 17x27', quantidade: 1, unidade: 'kg', valor: 13.99 },
    { item: 'Réguas 7cm', quantidade: 10, unidade: 'unidades', valor: 79.50 },
    { item: 'Alvenarite', quantidade: 5, unidade: 'litros', valor: 40.99 },
    { item: 'Impermeabilizante', quantidade: 1, unidade: 'galão', valor: 129.99 },
    { item: 'Mangueira elétrica', quantidade: 1, unidade: 'rolo', valor: 59.99 },
    { item: 'Cano 100mm', quantidade: 1, unidade: 'barra', valor: 68.94 },
    { item: 'Joelho 100mm', quantidade: 1, unidade: 'unidade', valor: 5.99 },
    { item: 'Cano 40mm', quantidade: 1, unidade: 'barra', valor: 35.94 },
    { item: 'Joelhos 40mm', quantidade: 4, unidade: 'unidades', valor: 4.40 },
    { item: 'Cano 25mm', quantidade: 2, unidade: 'barras', valor: 45.48 },
    { item: 'T 25', quantidade: 3, unidade: 'unidades', valor: 2.97 },
    { item: 'Joelho 25 c/ rosca', quantidade: 4, unidade: 'unidades', valor: 23.96 },
    { item: 'Joelhos 25', quantidade: 3, unidade: 'unidades', valor: 2.97 },
    { item: 'Registros pressão', quantidade: 2, unidade: 'unidades', valor: 80.00 },
    { item: 'Luva c/ rosca interna', quantidade: 2, unidade: 'unidades', valor: 1.58 },
    { item: 'Luva c/ rosca externa', quantidade: 2, unidade: 'unidades', valor: 11.98 },
  ],
  tijolo: [
    { item: 'Tijolos 9x14', quantidade: 570, unidade: 'unidades', valor: 565.00 },
    { item: 'Cimento', quantidade: 30, unidade: 'sacos', valor: 1120.00 },
    { item: 'Areia', quantidade: 2, unidade: 'metros', valor: 359.90 },
    { item: 'Brita', quantidade: 1.5, unidade: 'metros', valor: 300.00 },
    { item: 'Argamassa', quantidade: 2, unidade: 'metros', valor: 379.00 },
    { item: 'Ferro 8mm', quantidade: 10, unidade: 'barras', valor: 399.95 },
    { item: 'Ferro 10mm', quantidade: 4, unidade: 'barras', valor: 199.80 },
    { item: 'Estribos', quantidade: 150, unidade: 'unidades', valor: 147.00 },
    { item: 'Blocos 14x19x39', quantidade: 115, unidade: 'unidades', valor: 457.70 },
    { item: 'Tábuas 30cm', quantidade: 6, unidade: 'unidades', valor: 173.40 },
    { item: 'Réguas 15cm', quantidade: 6, unidade: 'unidades', valor: 83.70 },
    { item: 'Prego 17x27', quantidade: 1, unidade: 'kg', valor: 13.99 },
    { item: 'Réguas 7cm', quantidade: 10, unidade: 'unidades', valor: 79.50 },
    { item: 'Alvenarite', quantidade: 5, unidade: 'litros', valor: 40.99 },
    { item: 'Impermeabilizante', quantidade: 1, unidade: 'galão', valor: 129.99 },
    { item: 'Mangueira elétrica', quantidade: 1, unidade: 'rolo', valor: 59.99 },
    { item: 'Cano 100mm', quantidade: 1, unidade: 'barra', valor: 68.94 },
    { item: 'Joelho 100mm', quantidade: 1, unidade: 'unidade', valor: 5.99 },
    { item: 'Cano 40mm', quantidade: 1, unidade: 'barra', valor: 35.94 },
    { item: 'Joelhos 40mm', quantidade: 4, unidade: 'unidades', valor: 4.40 },
    { item: 'Cano 25mm', quantidade: 2, unidade: 'barras', valor: 45.48 },
    { item: 'T 25', quantidade: 3, unidade: 'unidades', valor: 2.97 },
    { item: 'Joelho 25 c/ rosca', quantidade: 4, unidade: 'unidades', valor: 23.96 },
    { item: 'Joelhos 25', quantidade: 3, unidade: 'unidades', valor: 2.97 },
    { item: 'Registros pressão', quantidade: 2, unidade: 'unidades', valor: 80.00 },
    { item: 'Luva c/ rosca interna', quantidade: 2, unidade: 'unidades', valor: 1.58 },
    { item: 'Luva c/ rosca externa', quantidade: 2, unidade: 'unidades', valor: 11.98 },
  ],
  laje : [
    { item: 'Vigotes 2,10m', quantidade: 8, unidade: 'unidades', valor: 243.60 },
    { item: 'Tijolos laje', quantidade: 80, unidade: 'unidades', valor: 119.20 },
    { item: 'Cimento', quantidade: 9, unidade: 'sacos', valor: 315.00 },
    { item: 'Areia', quantidade: 1, unidade: 'metro', valor: 189.00 },
    { item: 'Brita', quantidade: 1.5, unidade: 'metros', valor: 300.00 },
    { item: 'Malha de ferro 3,2', quantidade: 1, unidade: 'unidade', valor: 39.95 },
    { item: 'Ferro 8mm', quantidade: 3, unidade: 'barras', valor: 119.70 },
    { item: 'Estribos', quantidade: 37, unidade: 'unidades', valor: 37.00 },
  ]
};

export const laje = [
  { item: 'Vigotes 2,10m', quantidade: 8, unidade: 'unidades', valor: 243.60 },
  { item: 'Tijolos laje', quantidade: 80, unidade: 'unidades', valor: 119.20 },
  { item: 'Cimento', quantidade: 9, unidade: 'sacos', valor: 315.00 },
  { item: 'Areia', quantidade: 1, unidade: 'metro', valor: 189.00 },
  { item: 'Brita', quantidade: 1.5, unidade: 'metros', valor: 300.00 },
  { item: 'Malha de ferro 3,2', quantidade: 1, unidade: 'unidade', valor: 39.95 },
  { item: 'Ferro 8mm', quantidade: 3, unidade: 'barras', valor: 119.70 },
  { item: 'Estribos', quantidade: 37, unidade: 'unidades', valor: 37.00 },
];